In [28]:
import pandas as pd
import numpy as np

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [30]:
df = pd.read_csv('../3/train.csv', usecols=['Age', 'Fare', 'Survived'])

In [31]:
df.head()

,Survived,Age,Fare
0,0,22.0,7.2500
1,1,38.0,71.2833
2,1,26.0,7.9250
3,1,35.0,53.1000
4,0,35.0,8.0500


In [44]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [45]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42
)

In [46]:
X_train.shape

(712, 2)

In [47]:
X_test.shape

(179, 2)

In [48]:
y_train.shape

(712,)

In [49]:
y_test.shape

(179,)

In [50]:
X_train.head()

,Age,Fare
331,45.5,28.5000
733,23.0,13.0000
382,32.0,7.9250
704,26.0,7.8542
813,6.0,31.2750


In [51]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: Survived, dtype: int64

In [52]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [53]:
X_train_trf

array([[ 45.5   ,  28.5   ],
       [ 23.    ,  13.    ],
       [ 32.    ,   7.925 ],
       ...,
       [ 41.    ,  14.1083],
       [ 14.    , 120.    ],
       [ 21.    ,  77.2875]], shape=(712, 2))

In [54]:
from sklearn.linear_model import LogisticRegression

In [55]:
lr = LogisticRegression()
lr.fit(X_train_trf, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [56]:
y_pred = lr.predict(X_test_trf)

In [57]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.6480446927374302

In [62]:
from sklearn.impute import MissingIndicator
# MissingIndicator batata hai ki dataset me original missing values (NaN) kahan-kahan the

In [63]:
mi = MissingIndicator()
mi.fit(X_train)

,missing_values,nan
,features,'missing-only'
,sparse,'auto'
,error_on_new,True


In [65]:
mi.features_
# 👉 This shows the indices of columns in X_train where missing values were detected
# 👉 Example: array([0]) means column at index 0 (Age) had missing values
# 👉 It tells which original features were used to create missing-indicator features

array([0])

In [66]:
X_train_missing = mi.transform(X_train)

In [67]:
X_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [68]:
X_test_missing = mi.transform(X_test)

In [69]:
X_test_missing

array([[ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [70]:
X_test

,Age,Fare
709,NaN,15.2458
439,31.0,10.5000
840,20.0,7.9250
720,6.0,33.0000
39,14.0,11.2417
...,...,...
433,17.0,7.1250
773,NaN,7.2250
25,38.0,31.3875
84,17.0,10.5000


In [71]:
X_train

,Age,Fare
331,45.5,28.5000
733,23.0,13.0000
382,32.0,7.9250
704,26.0,7.8542
813,6.0,31.2750
...,...,...
106,21.0,7.6500
270,NaN,31.0000
860,41.0,14.1083
435,14.0,120.0000


In [73]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [74]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(X_train_trf2, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [75]:
y_pred = lr.predict(X_test_trf2)

In [76]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6480446927374302

In [79]:
si = SimpleImputer(add_indicator=True)

# 👉 SimpleImputer: missing values (NaN) ko mean/median/constant se fill karta hai
# 👉 add_indicator=True:
#    - ek extra binary column add karta hai
#    - 1 (True) = value missing thi
#    - 0 (False) = value present thi
# 👉 Benefit: model ko missingness ka pattern bhi learn karne milta hai

In [80]:
X_train = si.fit_transform(X_train)
X_test = si.transform(X_test)

In [81]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6480446927374302